// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line webapp/public/error.qtpl:2
package public

//line webapp/public/error.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line webapp/public/error.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line webapp/public/error.qtpl:2
func StreamError(qw422016 *qt422016.Writer, err string) {
//line webapp/public/error.qtpl:2
	qw422016.N().S(`<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><title>Ошибка - Apollo</title><meta name="viewport" content="width=device-width, initial-scale=1.0"><script src="https://telegram.org/js/telegram-web-app.js"></script><link rel="stylesheet" href="/static/css/style.css?v=1.6.0"></head><body><main id="swup" class="animated transition-fade"><div class="center column message"><svg class="icon" viewBox="0 0 24 24"><path d="M12,0A12,12,0,1,0,24,12,12.013,12.013,0,0,0,12,0Zm0,22A10,10,0,1,1,22,12,10.011,10.011,0,0,1,12,22Z"/><path d="M12,5a1,1,0,0,0-1,1v8a1,1,0,0,0,2,0V6A1,1,0,0,0,12,5Z"/><rect x="11" y="17" width="2" height="2" rx="1"/></svg><span class="small label">`)
//line webapp/public/error.qtpl:26
	qw422016.E().S(err)
//line webapp/public/error.qtpl:26
	qw422016.N().S(`</span></div></main></body></html>`)
//line webapp/public/error.qtpl:31
}

//line webapp/public/error.qtpl:31
func WriteError(qq422016 qtio422016.Writer, err string) {
//line webapp/public/error.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line webapp/public/error.qtpl:31
	StreamError(qw422016, err)
//line webapp/public/error.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line webapp/public/error.qtpl:31
}

//line webapp/public/error.qtpl:31
func Error(err string) string {
//line webapp/public/error.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line webapp/public/error.qtpl:31
	WriteError(qb422016, err)
//line webapp/public/error.qtpl:31
	qs422016 := string(qb422016.B)
//line webapp/public/error.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line webapp/public/error.qtpl:31
	return qs422016
//line webapp/public/error.qtpl:31
}
