// Code generated by qtc from "registration.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line webapp/public/registration.qtpl:2
package public

//line webapp/public/registration.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line webapp/public/registration.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line webapp/public/registration.qtpl:2
func StreamRegistration(qw422016 *qt422016.Writer) {
//line webapp/public/registration.qtpl:2
	qw422016.N().S(`<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><title>Регистрация - Apollo</title><meta name="viewport" content="width=device-width, initial-scale=1.0"><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script><script src="https://unpkg.com/swup@2.0.19/dist/swup.min.js"></script><script src="https://telegram.org/js/telegram-web-app.js"></script><link rel="stylesheet" href="/static/css/style.css?v=1.6.0"></head><body><main id="swup" class="animated transition-fade" no-return namespace="registration" main-button="ОТПРАВИТЬ ЗАЯВКУ"><form class="center column menu"><span>Регистрация</span><input type="text" name="first_name" placeholder="Имя" required><input type="text" name="last_name" placeholder="Фамилия" required></form></main><script src="/static/js/app.js?v=1.6.0"></script><script>Application.init();</script></body></html>`)
//line webapp/public/registration.qtpl:37
}

//line webapp/public/registration.qtpl:37
func WriteRegistration(qq422016 qtio422016.Writer) {
//line webapp/public/registration.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line webapp/public/registration.qtpl:37
	StreamRegistration(qw422016)
//line webapp/public/registration.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line webapp/public/registration.qtpl:37
}

//line webapp/public/registration.qtpl:37
func Registration() string {
//line webapp/public/registration.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line webapp/public/registration.qtpl:37
	WriteRegistration(qb422016)
//line webapp/public/registration.qtpl:37
	qs422016 := string(qb422016.B)
//line webapp/public/registration.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line webapp/public/registration.qtpl:37
	return qs422016
//line webapp/public/registration.qtpl:37
}

//line webapp/public/registration.qtpl:39
func StreamWait(qw422016 *qt422016.Writer) {
//line webapp/public/registration.qtpl:39
	qw422016.N().S(`<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><title>Ожидание - Apollo</title><meta name="viewport" content="width=device-width, initial-scale=1.0"><script src="https://telegram.org/js/telegram-web-app.js"></script><link rel="stylesheet" href="/static/css/style.css?v=1.6.0"></head><body><main id="swup" class="animated transition-fade" no-return><div class="center column message"><svg class="icon" viewBox="0 0 24 24"><path d="m9 24h-8a1 1 0 0 1 0-2h8a1 1 0 0 1 0 2z"/><path d="m7 20h-6a1 1 0 0 1 0-2h6a1 1 0 0 1 0 2z"/><path d="m5 16h-4a1 1 0 0 1 0-2h4a1 1 0 0 1 0 2z"/><path d="m13 23.955a1 1 0 0 1 -.089-2 10 10 0 1 0 -10.87-10.865 1 1 0 0 1 -1.992-.18 12 12 0 0 1 23.951 1.09 11.934 11.934 0 0 1 -10.91 11.951c-.03.003-.061.004-.09.004z"/><path d="m12 6a1 1 0 0 0 -1 1v5a1 1 0 0 0 .293.707l3 3a1 1 0 0 0 1.414-1.414l-2.707-2.707v-4.586a1 1 0 0 0 -1-1z"/></svg><span class="label">Ваша заявка ожидает рассмотрения</span></div></main></body></html>`)
//line webapp/public/registration.qtpl:70
}

//line webapp/public/registration.qtpl:70
func WriteWait(qq422016 qtio422016.Writer) {
//line webapp/public/registration.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
//line webapp/public/registration.qtpl:70
	StreamWait(qw422016)
//line webapp/public/registration.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line webapp/public/registration.qtpl:70
}

//line webapp/public/registration.qtpl:70
func Wait() string {
//line webapp/public/registration.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
//line webapp/public/registration.qtpl:70
	WriteWait(qb422016)
//line webapp/public/registration.qtpl:70
	qs422016 := string(qb422016.B)
//line webapp/public/registration.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
//line webapp/public/registration.qtpl:70
	return qs422016
//line webapp/public/registration.qtpl:70
}
