// Code generated by qtc from "empty.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line webapp/public/class/empty.qtpl:2
package class

//line webapp/public/class/empty.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line webapp/public/class/empty.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line webapp/public/class/empty.qtpl:2
func StreamEmpty(qw422016 *qt422016.Writer) {
//line webapp/public/class/empty.qtpl:2
	qw422016.N().S(`<main id="swup" class="animated transition-fade"><div class="center column message"><svg class="icon" viewBox="0 0 24 24"><path d="M23.271,9.419A15.866,15.866,0,0,0,19.9,5.51l2.8-2.8a1,1,0,0,0-1.414-1.414L18.241,4.345A12.054,12.054,0,0,0,12,2.655C5.809,2.655,2.281,6.893.729,9.419a4.908,4.908,0,0,0,0,5.162A15.866,15.866,0,0,0,4.1,18.49l-2.8,2.8a1,1,0,1,0,1.414,1.414l3.052-3.052A12.054,12.054,0,0,0,12,21.345c6.191,0,9.719-4.238,11.271-6.764A4.908,4.908,0,0,0,23.271,9.419ZM2.433,13.534a2.918,2.918,0,0,1,0-3.068C3.767,8.3,6.782,4.655,12,4.655A10.1,10.1,0,0,1,16.766,5.82L14.753,7.833a4.992,4.992,0,0,0-6.92,6.92l-2.31,2.31A13.723,13.723,0,0,1,2.433,13.534ZM15,12a3,3,0,0,1-3,3,2.951,2.951,0,0,1-1.285-.3L14.7,10.715A2.951,2.951,0,0,1,15,12ZM9,12a3,3,0,0,1,3-3,2.951,2.951,0,0,1,1.285.3L9.3,13.285A2.951,2.951,0,0,1,9,12Zm12.567,1.534C20.233,15.7,17.218,19.345,12,19.345A10.1,10.1,0,0,1,7.234,18.18l2.013-2.013a4.992,4.992,0,0,0,6.92-6.92l2.31-2.31a13.723,13.723,0,0,1,3.09,3.529A2.918,2.918,0,0,1,21.567,13.534Z"/></svg><span class="label">Пустой класс</span></div></main>`)
//line webapp/public/class/empty.qtpl:12
}

//line webapp/public/class/empty.qtpl:12
func WriteEmpty(qq422016 qtio422016.Writer) {
//line webapp/public/class/empty.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line webapp/public/class/empty.qtpl:12
	StreamEmpty(qw422016)
//line webapp/public/class/empty.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line webapp/public/class/empty.qtpl:12
}

//line webapp/public/class/empty.qtpl:12
func Empty() string {
//line webapp/public/class/empty.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line webapp/public/class/empty.qtpl:12
	WriteEmpty(qb422016)
//line webapp/public/class/empty.qtpl:12
	qs422016 := string(qb422016.B)
//line webapp/public/class/empty.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line webapp/public/class/empty.qtpl:12
	return qs422016
//line webapp/public/class/empty.qtpl:12
}
